[guppy_connection]
config = "dna_r9.4.1_450bps_hac"
host = "127.0.0.1"
port = 5555
procs = 4
inflight = 512

[conditions]
reference = "/path/to/reference.mmi"

[conditions.0]
name = "Control Condition"
control = true
min_chunks = 0
max_chunks = inf
targets = []
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "stop_receiving"
multi_off = "stop_receiving"
no_seq = "stop_receiving"
no_map = "stop_receiving"

[conditions.1]
name = "select_chr_21_22"
control = false
min_chunks = 0
max_chunks = inf
targets = ["chr21", "chr22"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
